name: "CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # replace with lints and integration tests
      - name: Dummy
        run: echo "All swell"